on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  hello:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: print
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}         
          
