on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  hello:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: print
        run: |
          ls
          echo ${{ github.event }}
          
