on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

env:
  MY_VAR: "init_value"

jobs:
  hello:
    runs-on: ubuntu-22.04

    outputs:
      var: ${{ steps.set-var.outputs.MY_VAR }}

    steps:
      - uses: actions/checkout@v4
      - name: Set Var
        id: set-var
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            my_var="updated_push"
          else
            my_var="updated"
          fi
          echo "MY_VAR=$my_var" >> $GITHUB_ENV
          echo "MY_VAR=$my_var" >> $GITHUB_OUTPUT

      - name: print
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ env.MY_VAR }}


  next-job:
    needs: hello
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: print
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}         
          echo ${{ env.MY_VAR }}
          echo ${{ needs.hello.outputs.var }}
      
  another-job:
    needs: [hello, next-job]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: print
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}         
          echo ${{ env.MY_VAR }}
          echo ${{ needs.hello.outputs.var }}
